### ISSUE TITLE
autoReload not working

### ISSUE THREAD

**Issue by FrancoisPerez** [HaNdTriX/webextension-toolbox#4]
Executing `npm run dev chrome` won't trigger the copy of autoReload.js at the root directory of the extension

**Comment by HaNdTriX** [comment]
If you are talking about the example you'll need to exec:  `$ npm run dev -- chrome`.
Otherwise do you have more infos?

**Comment by HaNdTriX** [comment]
Just released a new version (v0.0.6) your might might already got resolved.

**Comment by santialbo** [comment]
Same issue here, running `npm run dev -- chrome` doesn't create the autoReload.js file on `dist/chrome/`

I'm running the latest version of the toolbox (0.0.6)

**Comment by HaNdTriX** [comment]
Thanks a lot for your feedback!

I just released `v0.0.7`. This version improved the resolving of these assets. Does it resolve your issue?

https://github.com/HaNdTriX/webextension-toolbox/commit/a8d27aab548f6a49eae13ed478db8a840c476d85

**Comment by HaNdTriX** [comment]
Closing this issue since we are already at `v0.0.8`. If this issue is still present please reopen!

**Comment by JimMorrison723** [comment]
For me, after a fresh install, it still doesn't copy the scripts directory.
Generated the extension via `yo web-extension` , then run any of the following commands:
`npm run dev chrome`
`npm run dev -- chrome`
`webextension-toolbox dev chrome`

Windows10
Node: 9.3.0
NPM: 5.6.0
webextension-toolbox: 0.1.4
generator-web-extension: 0.0.5

**Comment by HaNdTriX** [comment]
We just published a beta release to tackle this issue.
If you want to check it out install it via:

```bash
npm install webextension-toolbox@next
```

**Comment by JimMorrison723** [comment]
i quickly checked it (not through fully, only chrome), and looks like it's working as intended 👍

**Comment by HaNdTriX** [comment]
@JimMorrison723 Thanks a lot for looking into it!
