### ISSUE TITLE
webextension polyfill not included

### ISSUE THREAD

**Issue by matthewgonzalez** [HaNdTriX/webextension-toolbox#6]
Hey, thanks for this tool; exactly what I need!

The compiler doesn't seem to be including the webextension polyfill. I'm getting `browser is not defined` errors in the console.

**Comment by HaNdTriX** [comment]
Thanks a lot for your feedback!

I just released v0.0.7. This version improved the resolving of these assets. Does it resolve your issue?

### Note

Since the `webextension-polyfill` is added by the `webpack.DefinePlugin` it is only added if the keyword `browser` was used somewhere in your code at compile time. Nevertheless you won't have access to it in your console, unless you  set it explicitly to the global namespace.

**Example:** `background.js`

```js
window.browser = browser
```

**Comment by matthewgonzalez** [comment]
Hmm, still experiencing the issue (see screens below). 

A clarification, I wasn't trying to call `browser` from the console, but was only seeing that error there as a result of it not being accessible in the default template code in `background.js`.

If you look at the sources in chrome devtools, Webpack doesn't seem to be including any of the webextension-polyfill code.

![background](https://user-images.githubusercontent.com/1775184/34888357-d0fa4df0-f77e-11e7-91f2-860b55f00aa5.jpg)

**Comment by matthewgonzalez** [comment]
Fixed with  680bffe67906bcd3c00a6490b84db6d60713a4c1

Thanks Henrik
